services:
  nginx:
    #image: nginx:1.27.0-alpine
    image: nginx-my
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_c
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./src:/usr/share/nginx/html
      - ./var/www/example.com/html:/var/www/example.com/html
    #env_file:
      #  - ./.env
